### ISSUE TITLE
possible help)

### ISSUE THREAD

**Issue by freedom1b2830** [floyd-fuh/TMSJSPGE#1]
While searching for a solution to fuzzing java code, I came across jqf and its related article at (https://www.modzero.com/modlog/archives/2018/09/20/java_bugs_with_and_without_fuzzing/index.html)
you had a problem writing a policy for java.
I have a simple solution for finding affected filesystem paths: use ```strace -ff```
this will show every application syscall s
you only need to parse: reading/writing paths

**Comment by floyd-fuh** [comment]
I did a couple of minor updates to the content of that link, but as I'm not working there anymore I did it on https://www.floyd.ch/?p=1090 where I've cross-posted when the article came out. Also make sure you read my follow-up post on https://www.pentagrid.ch/en/blog/fuzzing_java_with_jqf/ . It's worth looking at ZEST 

About the strace: True, but I would still need to write the rules then with cut, grep etc. but yeah, probably a better solution, this was more of a rushed project (hence the ugly name). I was mainly disappointed there is no tool that writes the minimum policy automatically.
